# Generated by Django 3.2.8 on 2021-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainFlagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('ValidFrom', models.DateTimeField()),
                ('ValidUntil', models.DateTimeField()),
            ],
            options={
                'db_table': 'domainFlag',
            },
        ),
    ]
