# Generated by Django 3.2.8 on 2021-11-05 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
        ('domainFlag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainflagmodel',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='domainflag', to='domain.domainmodel'),
            preserve_default=False,
        ),
    ]
