# Generated by Django 3.2.8 on 2021-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainFlag', '0002_domainflagmodel_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainflagmodel',
            name='ValidUntil',
            field=models.DateTimeField(null=True),
        ),
    ]
