# Generated by Django 3.2.8 on 2021-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmodel',
            name='DeletionDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='domainmodel',
            name='ExpirationDate',
            field=models.DateTimeField(null=True),
        ),
    ]
